"""
Django settings for poma2 project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from .localenv import *
import datetime
import pytz
import collections

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&a@qm_fg$q&c3@983sh20ikf911_2dvhn5oq6s$m_t-^1)@g4x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.100.104', 'localhost', '127.0.0.1', 'poma', '192.168.100.2', '186.137.9.13', '192.168.100.129']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'skynet.apps.SkynetConfig',
    'wc_liaison.apps.WcLiaisonConfig',
    'slaicer.apps.SlaicerConfig',
    'overseer',
    'rest_framework',
    'django_celery_results',
    'django_celery_beat',
    'django.contrib.sites',
    'prettyjson',
    'corsheaders',
]

REST_FRAMEWORK = {
'FORM_METHOD_OVERRIDE': None,
'FORM_CONTENT_OVERRIDE': None,
'FORM_CONTENTTYPE_OVERRIDE': None,
'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ],
 'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'poma2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['poma2/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'poma2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'poma',
        'USER': 'poma',
        'PASSWORD': 'EgCn7f8HMiufkO',
        'HOST': '127.0.0.1',
        'PORT': '',
        'OPTIONS': {
           'sslmode': 'disable',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Deshabilitamos CORS para facilitar el desarrollo del overseer
CORS_ORIGIN_ALLOW_ALL = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',  # change debug level as appropiate
            'propagate': False,
        },
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = 'media/'
MEDIA_URL = '/media/'

SITE_ID = 1
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440 * 100


#Celery config
CELERY_RESULT_BACKEND = 'django-db'
CELERY_BROKER_URL = 'amqp://'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SOFT_TIME_LIMIT = 600*3
CELERY_CHORD_UNLOCK_MAX_RETRIES = 60
CELERY_PREFETCH_MULTIPLIER = 1
CELERY_QUEUES = ('celery')
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

# Task planning configuration
TIME_ZONE = 'America/Argentina/Buenos_Aires'
## Forbidden zones configuration
forbidden_zone = collections.namedtuple('zone', 'start duration')
FORBIDDEN_ZONES = [forbidden_zone(start=21, duration=12)]
## Send a beep to printers that are awaiting for human intervention (interval)
BEEP_THRESHOLD_COUNT = 60000

# Temp WooCommerce API Key

WOOCOMMERCE_URL = "https://tercerojo.creame3d.com"
CONSUMER_KEY = "ck_b400211280df3fbb2fa7a37c1eec68b0de8f169a"
CONSUMER_SECRET = "cs_807f8bf3bd27bcd7c1c6c6d097504c7a924f520a"
